### ISSUE TITLE
Unable to use javascript loop on "This Is the Run"

### ISSUE THREAD

**Issue by naterfb** [lightpohl/gb-dl#7]
I am trying to run this javascript loop (I removed my API key and added in comments for the start/end so that I don't confuse myself:

```js
let execSync = require("child_process").execSync;

// Replace `YOUR_API_KEY` with the key from https://www.giantbomb.com/api
let apiKey = "YOUR_API_KEY";

/*
  Finding the `endingEpisode` is a little tricky if there are multiple seasons
  of a show, but you can add the `--info` command with different `--video-number` numbers
  to find it before running the script.
*/
let showName = "This Is The Run";
let startingEpisodeNumber = 50; // LATEST episode to download
let endingEpisode = 52; // FIRST episode to download

/*
  For simplicity, we're going to download in reverse order, but you could
  switch it by adjusting the `for` loop below.
*/
for (let i = startingEpisodeNumber; i <= endingEpisode; i++) {
  try {
    execSync(
      `npx gb-dl --api-key ${apiKey} --show-name ${showName} --video-number ${i}`,
      { stdio: "inherit" } // this will allow us to see the console output as it downloads
    );
  } catch (error) {
    console.error(error);
    console.log("Something happened! Moving onto the next video.");
  }
}
```

I get this error message (edited to remove API key):

PS D:\Downloads\GB> node .\titr.js
npx: installed 38 in 3.925s
no video found for query
Error: Command failed: npx gb-dl --api-key YOUR_API_KEY --show-name This Is The Run --video-number 50
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (D:\Downloads\GB\titr.js:33:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5364,
  stdout: null,
  stderr: null
}
Something happened! Moving onto the next video.
npx: installed 38 in 3.035s
no video found for query
Error: Command failed: npx gb-dl --api-key YOUR_API_KEY --show-name This Is The Run --video-number 51
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (D:\Downloads\GB\titr.js:33:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 7304,
  stdout: null,
  stderr: null
}
Something happened! Moving onto the next video.
npx: installed 38 in 3.207s
no video found for query
Error: Command failed: npx gb-dl --api-key YOUR_API_KEY --show-name This Is The Run --video-number 52
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (D:\Downloads\GB\titr.js:33:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 16288,
  stdout: null,
  stderr: null
}
Something happened! Moving onto the next video.
PS D:\Downloads\GB>

**Comment by lightpohl** [comment]
Hey @naterfb - I think I found the issue. Looks like you need to add double quotes around the show name in the script where it calls `gb-dl`. The working version for me looks like this on that line:

```js
`npx gb-dl --api-key ${apiKey} --show-name "${showName}" --video-number ${i}`
```

Let me know if that fixes it for you!

Edit: I updated the example script for Mass Alex to include those double quotes.

**Comment by naterfb** [comment]
Yes, that seems to in fact do the trick. What interesting is that this appears to be an inconsistent issue because other shows (such as "Steal My Sunshine") that ostensibly would require quotes do not. Thanks!
